name: App CI

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.12.6
        uses: actions/setup-python@v5
        with:
          python-version: 3.12.6

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Install dependencies in venv
        run: |
          pip install -r requirement.txt
        shell: bash

      - name: Start MySQL
        run: |
          sudo apt install mariadb-server

      - name: Login my sql
        run: |
          sudo mariadb -e "CREATE USER 'dbuser'@'127.0.0.1' IDENTIFIED BY 'password'"
          sudo mariadb -e "GRANT ALL PRIVILEGES ON *.* TO 'dbuser'@127.0.0.1"

      - name: Create User in database
        run: |
          sudo mysql -e "CREATE USER 'dbuser'@'localhost' IDENTIFIED BY 'password'"
          sudo mysql -e "GRANT ALL PRIVILEGES ON *.* TO 'dbuser'@localhost IDENTIFIED BY 'password'"

      - name: Create env user
        run: |
          touch .env
          echo "DB_USERNAME=dbuser">>.env
          echo "DB_PASSWORD=password">>.env
          echo "DB_NAME=test">>.env
          echo "DB_HOST=localhost">>.env
          echo "DB_PORT=3306">>.env

      - name: Python unittest
        run: |
          python -m unittest discover -s app/tests -p 'test_healthcheck.py'

      - name: Run HealthCheck Tests
        run: |
          python -m unittest discover -s app/tests -p 'test_healthcheck.py' &> user_output.log
          cat user_output.log
          if grep -i 'AssertionError' user_output.log; then
            echo 'Test failed due to an AssertionError!'
            exit 1c
          fi
        shell: bash

      - name: Run User API Tests
        run: |
          python -m unittest discover -s app/tests -p 'test_user.py' &> user_output.log
          cat user_output.log
          if grep -i 'AssertionError' user_output.log; then
            echo 'Test failed due to an AssertionError!'
            exit 1
          fi
        shell: bash
