name: Flask App CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.12.6
        uses: actions/setup-python@v5
        with:
          python-version: 3.12.6

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Install dependencies in venv
        run: |
          pip install -r requirement.txt
        shell: bash

      - name: Install MySQL DB
        uses: mirromutth/mysql-action@v1.1
        with:
          host port: 3306
          container port: 3306
          character set server: "utf8"
          collation server: "utf8_general_ci"
          mysql version: "8.0"
          mysql database: "test"
          mysql root password: "password"
          mysql user: "dbuser"
          mysql password: "password"

      - name: Start MySQL
        run: |
          sudo apt install mysql-server -y
          sudo systemctl start mysql

      # - name: Create User in database
      #   run: |
      #     sudo mysql -e "CREATE USER 'dbuser'@'localhost' IDENTIFIED BY 'password'"
      #     sudo mysql -e "GRANT ALL PRIVILEGES ON *.* TO 'dbuser'@localhost IDENTIFIED BY 'password'"

      - name: Create env user
        run: |
          touch .env
          echo "DB_USERNAME=dbuser">>.env
          echo "DB_PASSWORD=password">>.env
          echo "DB_NAME=test">>.env
          echo "DB_HOST=localhost">>.env
          echo "DB_PORT=3306">>.env

      - name: Run
        run: |
          python run.py

      - name: Run HealthCheck Tests
        run: |
          python -m unittest discover -s app/tests -p 'test_healthcheck.py' &> user_output.log
          cat user_output.log
          if grep -i 'AssertionError' user_output.log; then
            echo 'Test failed due to an AssertionError!'
            exit 1
          fi
        shell: bash

      # Run User API Tests and check for errors
      - name: Run User API Tests
        run: |
          python -m unittest discover -s app/tests -p 'test_user.py' &> user_output.log
          cat user_output.log
          if grep -i 'AssertionError' user_output.log; then
            echo 'Test failed due to an AssertionError!'
            exit 1
          fi
        shell: bash
